### ISSUE TITLE
Shortcuts for deleting and editing? show URL by default?

### ISSUE THREAD

**Issue by victor-50** [tiancihe/bookmark-manager#11]
Hi, use this primarily for my bookmark toolbar, trying to shorten or remove titles and for cleaning up, Thus it would be handy if urls are always visible, not only when clicked. Then if "f2" would make the title accessible for  editing (as in Windows explorer) would save a lot of time. Finally, removing by pressing del or ctrl-del would be great. TIA

**Comment by tiancihe** [comment]
Great suggestions, but i'm kind of occupied with work right now, i'll implement these features when i get some free time.

**Comment by tiancihe** [comment]
@victor-50 v0.9.0 is out, there is a switch control to make urls always visible, and shortcut to delete bookmarks/folders (cmd + backspace on mac, del on windows) is also added, as of the "f2" thing, maybe next version

**Comment by victor-50** [comment]
Thanks!
