### ISSUE TITLE
Create folder?

### ISSUE THREAD

**Issue by pm64** [tiancihe/bookmark-manager#12]
I noticed this excellent add-on lacks a "create folder" feature. Is this due to an API limitation? I'd like to see the option to create a folder both in context menus and the 3-dot menu.

**Comment by tiancihe** [comment]
just right click anywhere blank, you'll find it in the context menu
![image](https://user-images.githubusercontent.com/36734012/116511160-992ab200-a8f8-11eb-813d-88a26d7dc32f.png)
