### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ARMOUR17** [tiancihe/bookmark-manager#13]
HI
please ioen bookmark in new tab and in background open .
after double click in bookmark open in new tab in background
.
optimize speed
persian font optimize.

**Comment by tiancihe** [comment]
i don't quite understand, please describe it with more detail

**Comment by ARMOUR17** [comment]
hi
According to the video, after double-clicking, the site should open in the background
Expand the graphics part of the program and increase the features of the program
The plugin is very useful, I am waiting for new changes
see this video
https://www.mediafire.com/file/12fwhlqz9cq4c5x/Rec_0003.mp4/file
regurds

**Comment by ARMOUR17** [comment]
hi
I am waiting for the plugin to be developed and improved
king regurds

**Comment by tiancihe** [comment]
> hi
> According to the video, after double-clicking, the site should open in the background
> Expand the graphics part of the program and increase the features of the program
> The plugin is very useful, I am waiting for new changes
> see this video
> https://www.mediafire.com/file/12fwhlqz9cq4c5x/Rec_0003.mp4/file
> regurds

I don't think that's the expected behaviour in chrome, maybe you have set double click map to middle mouse click, and yes, if you want the bahaviour shown in you video, you can always use middle mouse click, double click in my current setup (macos + chrome) will open a new tab immediately
