### ISSUE TITLE
resize left part of window

### ISSUE THREAD

**Issue by lazymonkey2** [tiancihe/bookmark-manager#16]
please can you implement resizing of the left part of the winodw? 
(the one containing the bookmark tree with the various folders).
I have many nested folders, and the size is too small to see all the folders.
Thanks.

**Comment by ghost** [comment]
Yes please, this would indeed be a great addition.
I have some long folder names and presently they are wrapping and that is distorting the layout  :(
If not able to add resizing, is it possible to simply make the left-pane 2 or 3 times as wide as it is now?
Maybe add an option to increase width by % or by X (i.e. 2x, 3x, 4x, etc.)

**Comment by tiancihe** [comment]
this feature is added in the latest 1.0.0 version which is awaiting review

**Comment by lazymonkey2** [comment]
thank you.

**Comment by lazymonkey2** [comment]
Hello,
I have v1.2.1 but the left part is not resizing.

**Comment by tiancihe** [comment]
> Hello, I have v1.2.1 but the left part is not resizing.

try to move your cursor around, it is invisible until you hover over it

**Comment by lazymonkey2** [comment]
I've tried but it doesn't resize.

![image](https://github.com/tiancihe/bookmark-manager/assets/26486758/a750d4aa-37bf-473b-84c0-4c98a15c13e9)

**Comment by tiancihe** [comment]
> I've tried but it doesn't resize.
> 
> ![image](https://private-user-images.githubusercontent.com/26486758/313455690-a750d4aa-37bf-473b-84c0-4c98a15c13e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDY1MDUsIm5iZiI6MTcxMDc0NjIwNSwicGF0aCI6Ii8yNjQ4Njc1OC8zMTM0NTU2OTAtYTc1MGQ0YWEtMzdiZi00NzNiLTg0YzAtNGM5OGExNWMxM2U5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA3MTY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4YzA1ZTRlNGRmYzI5ZWE0YTE0YTU1YmJiYzQ3ODczYmYzYzk2N2VlOGQxMTE3OTEyMTdhYTAwZDkxM2Q0MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._OKehDkLwzCy12nyTPfPirFQNXXnosherAFggNAhUhM)

your cursor should change to a crosshair icon while hovering over the splitter, then hold down your left mouse button, and drag it left or right to resize the panel

if it is not working, try to upgrade your firefox to the latest version, i've tested on my own windows pc and macbook, works fine

**Comment by lazymonkey2** [comment]
yes, the cursor changes to a crosshair (the screenshot doesn't show the cursor).
then I click and try to move it, but it doesn't move.

**Comment by lazymonkey2** [comment]
it works now, but I had to uninstall and reinstall the extension.
