### ISSUE TITLE
Cache favicons

### ISSUE THREAD

**Issue by tiancihe** [tiancihe/bookmark-manager#7]

**Comment by tiancihe** [comment]
Solution 1:

use fetch API to get the favicon and get the blob response, then use FileReader to get the result

but the google favicon service does not contains Access-Control-Allow-Origin, have to set mode to "no-cors"

resulting in the blob response we get is of size 0

so this solution does not work

```typescript
fetch("http://www.google.com/s2/favicons?domain_url=https%3A%2F%2Feloquentjavascript.net", { mode:"no-cors" })
    .then(res => {
        console.log(res) // type: "opaque"
        return res.blob()
    })
    .then(blob => {
        console.log(blob) // size: 0
        const reader = new FileReader()
        reader.addEventListener("load", () => console.log(reader.result))
        reader.readAsDataURL(blob)
    })
    .catch(console.error)
```

Solution 2:

listen for the img element's load event, grab its currentTarget (the img element itself), use canvas to get the data url

this fails too, because the browser does not allow this kind of action due to security concern

```typescript
function getFaviconDataURL(image: HTMLImageElement) {
    const canvas = window.document.createElement("canvas")
    canvas.width = 16
    canvas.height = 16
    const context = canvas.getContext("2d")
    context?.drawImage(image, 0, 0)
    return canvas.toDataURL() // results in an error: SecurityError: The operation is insecure.
}

<img
    onLoad={e => {
        console.log(getFaviconDataURL(e.currentTarget))
    }}
/>
```

**Comment by ghost** [comment]
Solution 3: provide an option to disable favicon fetching.
Several Firefox extensions which deal with the user's favicons offer the option to fetch or not favicons.
Bookmark Manager 0.8.1 is just what I need, brilliant, but I cannot use it because it calls `https://www.google.com/s2/favicons?domain=` every time I open a folder.
There is of course the privacy concern but also the fact that some users simply block favicons on their browser.
I'm really looking forwards for such an option because otherwise I just cannot use it.

**Comment by tiancihe** [comment]
I'm considering adding a standalone settings pane, favicon feature will be able to turn off via a switch control.

**Comment by ghost** [comment]
@tiancihe , 

> I'm considering adding a standalone settings pane, favicon feature will be able to turn off via a switch control.

I stay tuned and looking forwards, that will be great.

**Comment by tiancihe** [comment]
@Cade66 v0.9.0 is out, there is a switch control to enable or disable favicons now

**Comment by ghost** [comment]
Bookmark Manager v0.9.0 tested, approved, adopted! Handles disabling favicons + other improvements. La belle vie :=)

**Comment by ghost** [comment]
@tiancihe I just realized that if favicons are indeed not displayed when _Disable favicon_  is checked, connections to Google are nevertheless established. I have to remove Bookmark Manager v0.9.0, a pity.

**Comment by tiancihe** [comment]
> @tiancihe I just realized that if favicons are indeed not displayed when _Disable favicon_ is checked, connections to Google are nevertheless established. I have to remove Bookmark Manager v0.9.0, a pity.

Thanks for reporting the issue, will be fixed in a patch version.
